name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    # Make sure you put workflow kit action on top of all the steps 
    - name: Collect Workflow Telemetry
      uses: runforesight/foresight-workflow-kit-action@v1
      with:
        api_key: ${{ secrets.THUNDRA_APIKEY}}

    - name: tests
      uses: actions-rs/cargo@v1
      run: cargo test


    # Make sure you put test kit action after your test execution step 
    - name: Analyze Test and/or Coverage Results
      uses: thundra-io/foresight-test-kit-action@v1
      with:
        api_key: ${{ secrets.THUNDRA_APIKEY}}
          #test_framework: <test_framework_optional>
          #test_path: <test_results_path_optional>
          #coverage_format: <coverage_format_optional>
          #coverage_path: <coverage_results_path_optional>

